### ISSUE TITLE
Include the sourcedialog plugin

### ISSUE THREAD

**Issue by coret** [Daniel-KM/Omeka-S-module-DataTypeRdf#1]
The module installs a version of the CKE Editor which differs in an important way with the "default" CKE Editor (used for editing pages): the sourcedialog plugin is not included or enabled. So a users can't edit the source code of HTML inputfields (including pages).

Can this sourcedialog plugin be included and enabled in this module?

See also https://forum.omeka.org/t/where-did-the-option-go-to-edit-the-html-of-a-page/17848/2

**Comment by coret** [comment]
On further inspection of the code, I see this module doesn't install a version of the CKE Editor, so it's just configuration of the CKE Editor that's changed (sourcedialog plugin isn't enabled as in the default config of Omeka S).

**Comment by pprw** [comment]
same problem here.

**Comment by coret** [comment]
seems fixed in version 3.4.7!
